version: '3.7'

services:
  database:
    image: postgres:14-alpine
    container_name: auxilium-gpt-fallback-db 
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

